In [1]:
import numpy as np

X = np.array([[3,5], [5,1], [10,2]], dtype=float)
X = X / np.amax(X, axis=0)
y = np.array([[75], [82], [93]], dtype = float)
y = y /100

#인공신경망 클래스
class Artificial_Neural_Networks():
    
    #초기화
    def __init__(self):
        #입력층, 은닉층, 출력층의 노드 개수 정하기
        self.input_layer_size = int(input("Input_Layer_Size : "))
        self.hidden_layer_size = int(input("Hidden_Layer_Size : "))
        self.output_layer_size = int(input("Output_Layer_Size : "))
        self.lr = 20
        
        #입력층 -> 은닉층의 가중치, 편향 랜덤 설정
        self.W1 = np.random.randn(self.input_layer_size, self.hidden_layer_size)
        #은닉층 -> 출력층의 가중치, 편향 랜덤 설정
        self.W2 = np.random.randn(self.hidden_layer_size, self.output_layer_size)
    
    #순전파   
    def forward(self, X):
        #Y = W(1) * X
        self.z2 = np.dot(X, self.W1)
        self.a2 = self.sigmoid(self.z2)
        #Y = W(2) * X
        self.z3 = np.dot(self.a2, self.W2)
        yHat = self.sigmoid(self.z3)
        return yHat
     
    #시그모이드 함수
    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))
    
    #비용 함수  
    def cost_function(self, X_data, Y):
        self.yHat = self.forward(X_data)
        loss = (1 / self.input_layer_size) * sum((y-self.yHat)**2)
        return loss
    
    #시그모이드 함수의 미분
    def sigmoid_prime(self, z):
        return np.exp(-z) / ((1 + np.exp(-z))**2)    
   
    #역전파 과정
    def cost_function_prime(self, X, y):
        self.yHat = self.forward(X)
        delta3 = np.multiply(-(y - self.yHat), self.sigmoid_prime(self.z3))
        d_loss_d_W2 = np.dot(self.a2.T, delta3)
        
        delta2 = np.dot(delta3, self.W2.T) * self.sigmoid_prime(self.W2)
        d_loss_d_W1 = np.dot(X.T, delta2)
        return d_loss_d_W1, d_loss_d_W2
    
    def back_proc(self, dldw1, dldw2):
        self.W1 -= (self.lr * dldw1)
        self.W2 -= (self.lr * dldw2)
        return self.W1, self.W2

In [2]:
NN = Artificial_Neural_Networks()
for _ in range(2000):
    print("yHat : ", "\n", NN.forward(X))
    print("원래Y : ", "\n", y)
    cost1 = NN.cost_function(X,y)
    print("loss1 : ", cost1)
    a, b = NN.cost_function_prime(X, y)
    NN.W1, NN.W2 = NN.back_proc(a, b)
    cost2 = NN.cost_function(X, y)
    print("loss2 : ", cost2)


Input_Layer_Size :  2
Hidden_Layer_Size :  3
Output_Layer_Size :  1


yHat :  
 [[0.50701697]
 [0.46354056]
 [0.41974226]]
원래Y :  
 [[0.75]
 [0.82]
 [0.93]]
loss1 :  [0.22323352]
loss2 :  [0.04859461]
yHat :  
 [[0.99834221]
 [0.99587797]
 [0.99769273]]
원래Y :  
 [[0.75]
 [0.82]
 [0.93]]
loss1 :  [0.04859461]
loss2 :  [0.04855485]
yHat :  
 [[0.99828691]
 [0.99575972]
 [0.9976153 ]]
원래Y :  
 [[0.75]
 [0.82]
 [0.93]]
loss1 :  [0.04855485]
loss2 :  [0.04851265]
yHat :  
 [[0.99822803]
 [0.99563443]
 [0.99753286]]
원래Y :  
 [[0.75]
 [0.82]
 [0.93]]
loss1 :  [0.04851265]
loss2 :  [0.04846778]
yHat :  
 [[0.99816522]
 [0.99550147]
 [0.99744494]]
원래Y :  
 [[0.75]
 [0.82]
 [0.93]]
loss1 :  [0.04846778]
loss2 :  [0.04841999]
yHat :  
 [[0.9980981 ]
 [0.99536011]
 [0.99735097]]
원래Y :  
 [[0.75]
 [0.82]
 [0.93]]
loss1 :  [0.04841999]
loss2 :  [0.048369]
yHat :  
 [[0.99802621]
 [0.99520955]
 [0.99725035]]
원래Y :  
 [[0.75]
 [0.82]
 [0.93]]
loss1 :  [0.048369]
loss2 :  [0.04831446]
yHat :  
 [[0.99794905]
 [0.99504885]
 [0.99714236]]
원래Y :  
 [[0.75]
 [0.82]
 [0.93]]
